# Generated by Django 4.2.6 on 2023-12-20 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_district_name', models.CharField(max_length=255)),
            ],
            managers=[
                ('admin_districts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=255)),
                ('admin_district', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='address_book.administrativedistrict')),
            ],
            managers=[
                ('districts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StreetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_type', models.CharField(max_length=255)),
            ],
            managers=[
                ('street_types', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StreetsBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=255)),
                ('index', models.CharField(max_length=255)),
                ('district', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='address_book.district')),
                ('street_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='address_book.streettype')),
            ],
            managers=[
                ('streets', django.db.models.manager.Manager()),
            ],
        ),
    ]
