# Generated by Django 4.2.6 on 2023-11-25 13:29

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='administrativedistrict',
            managers=[
                ('admin_districts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='district',
            managers=[
                ('districts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='streetsbook',
            managers=[
                ('streets', django.db.models.manager.Manager()),
            ],
        ),
    ]
