# Generated by Django 4.2.6 on 2023-11-25 13:49

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0002_alter_administrativedistrict_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativedistrict',
            name='district',
        ),
        migrations.RemoveField(
            model_name='district',
            name='street',
        ),
        migrations.RemoveField(
            model_name='streetsbook',
            name='street_type',
        ),
        migrations.AddField(
            model_name='district',
            name='admin_district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='address_book.administrativedistrict'),
        ),
        migrations.AddField(
            model_name='streetsbook',
            name='district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='address_book.district'),
        ),
        migrations.CreateModel(
            name='StreetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_type', models.CharField(max_length=255)),
                ('street', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='address_book.streetsbook')),
            ],
            managers=[
                ('street_types', django.db.models.manager.Manager()),
            ],
        ),
    ]
