# Generated by Django 4.2.6 on 2023-12-20 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_level', models.IntegerField()),
                ('level', models.CharField(max_length=255)),
            ],
            managers=[
                ('levels', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_level', models.IntegerField()),
                ('level', models.CharField(max_length=255)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.activitylevel1')),
            ],
            managers=[
                ('levels', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLevel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_level', models.IntegerField()),
                ('level', models.CharField(max_length=255)),
                ('descript_level', models.TextField(null=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.activitylevel2')),
            ],
            managers=[
                ('levels', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=255, unique=True)),
            ],
            managers=[
                ('types', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_id', models.IntegerField()),
                ('address', models.TextField()),
                ('districts', models.TextField(null=True)),
                ('schedule_active', models.TextField(null=True)),
                ('schedule_past', models.TextField(null=True)),
                ('schedule_plan', models.TextField(null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.activitylevel3')),
            ],
            managers=[
                ('groups', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='activitylevel1',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.activitytypes'),
        ),
    ]
