version: '3.9'
services:
  web:
    build: .
    container_name: web
    command: sh -c "./create_db.sh"
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0.36
    container_name: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - '3309:3306'
    env_file: .env
    restart: always
    volumes:
      - ./mysql-django:/var/lib/mysql

volumes:
  mysql-django:
